### ISSUE TITLE
SQL Error when Permanently Deleting Posts

### ISSUE THREAD

**Issue by hymenoptera** [amwelles/mybb-threadlog#8]
I've successfully installed this on a forum running Mybb version 1.8.27, but I've run into an issue where I can't permanently delete posts; soft deleting, restoring, etc. all seem to work as intended.

Any help would be appreciated.

> MyBB has experienced an internal SQL error and cannot continue.
> 
> SQL Error:
>     1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') AND pid != 10' at line 2
> Query:
>     SELECT distinct uid from `mybb8s_posts` WHERE tid=4) AND pid != 10

**Comment by taylornmount** [comment]
https://github.com/amwelles/mybb-threadlog/blob/be6f4803c677876732c61e8a5d2ada4ac5b40f23/inc/plugins/threadlog.php#L284

The issue is in the above.

**Should be fixable by altering that line from this:**
`WHERE tid={$post['tid']}) AND pid != {$pid}");`
_(note the odd `)` behind tid)_

**To this:**
`WHERE tid={$post['tid']} AND pid != {$pid}");`
